### ISSUE TITLE
Broken: trackpath() no longer working with raster package

### ISSUE THREAD

**Issue by AustinGreene** [aharmer/pathtrackr#10]
It appears that a function was updated in the raster library and is now causing trackpath to fail. Ran a fresh install of everything tonight and trackpath fails every time with the following error...

`
Error in validityMethod(object) : invalid extent: xmin >= xmax
`

**Comment by aharmer** [comment]
Hi,
I am unable to replicate your error message after updating all packages. At what point in the process is it failing? i.e. when you are selecting the arena and animal or during tracking?

I am assuming something is going wrong when you are defining your boxes around the arena and the animal as your minimum x value is greater than your maximum x value. Can I suggest trying once more after a clean install and if its still not working, attach a screen shot of your first frame and where you are trying define the arena and animal boundaries?

**Comment by AustinGreene** [comment]
Issue solved, though I can't determine why. It appears the raster package was updated and everything is now running fine.
