### ISSUE TITLE
Error in ellipsoidhull(mat) :    computed some negative or all 0 probabilities

### ISSUE THREAD

**Issue by calebvogt** [aharmer/pathtrackr#13]
The following video continually throws the above error at the 35% tracking mark when using the trackPath function. Any ideas how to overcome this? I tracked ellipsoidhull(mat) down to the EllPar.R function

https://drive.google.com/drive/folders/1x9G0wAjXHK1f3_xO3b8cG6eN4o2A-aY6?usp=sharing

Thanks!

**Comment by aharmer** [comment]
Hi, not entirely sure but I suspect it is a resolution problem with the blob size dropping below a certain threshold and preventing the fitting of an ellipsoid hull. I get the same error as you, but if I resplit the vide at a higher resolution (xpix = 640) tracking worked fine.
