### ISSUE TITLE
Error in tracking

### ISSUE THREAD

**Issue by dhanya-bharath** [aharmer/pathtrackr#15]
Hi,

I've just started using the software and I got the following message in R.
Generating background reference frame...

  |::::::::::::::::::::::::::::::::::::::::::::::::::| 100%
  |::::::::::::::::::::::::::::::::::::::::::::::::::| 100%

Tracking animal...

  |                                                  |   0%Error in thresh(isoblur(as.cimg(tbox), blur)) : 
  filter width exceeds picture width

Could anyone help me out with this?
Thanks,
Dhanya

**Comment by aharmer** [comment]
Hi, this is probably due to using a very small tracking box size. You could try increasing the tracking box size, and also splitting you video at a higher resolution if the animals are very small relative to the frame size.

**Comment by dhanya-bharath** [comment]
Okay, thanks! Will try that. 
Also, how would you suggest going about deciding on the optimum splitting rate? I assume this would be dependent on how fast the animal moves, but is there a rough guide I can go with?

**Comment by aharmer** [comment]
Hi, as you say splitting rate really depends on the speed and movement pattern of your animal. A bit of trial and error will give you your optimal rate. It is really a trade off between accuracy and processing time.
