### ISSUE TITLE
splitVideo not working with .tif videos created with imagej

### ISSUE THREAD

**Issue by hummuscience** [aharmer/pathtrackr#16]
Using a .tif video/stack created with imagej does not work. Turning that video into an .avi file works. Not sure if it is a problem with R or ffmprg

**Comment by aharmer** [comment]
splitVideo is looking for a video codec via FFmpeg. I'm not sure if tif stacks have a codec associated with them so it throws an error. You can use the avi option as you say, or of you already have individual image files, convert them to a compressed form for speed and skip the splitVideo step.
