### ISSUE TITLE
R installation error

### ISSUE THREAD

**Issue by mulligan123** [aharmer/pathtrackr#17]
Hello! I'm trying to install pathtrackr on Rstudio, but I get this error message. I actually gave up and tried to download a different tracking program, but I got the same error message - so now I'm thinking it's a more systematic problem with installing packages from github. Any thoughts? Thanks!

  - Chris

* installing *source* package ‘pathtrackr’ ...
** R
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/imager/libs/imager.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/imager/libs/imager.so, 6): Library not loaded: /opt/X11/lib/libX11.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/imager/libs/imager.so
  Reason: image not found
ERROR: lazy loading failed for package ‘pathtrackr’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/pathtrackr’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/1x/m9p98yxs74xgfbh5ykwjsfrh0000gn/T//RtmpTSAFEB/filea8481c6fac6a/pathtrackr_1.2.3.tar.gz’ had non-zero exit status

**Comment by mulligan123** [comment]
I'm using R version 3.5.1 on a mac High Sierra

**Comment by aharmer** [comment]
This is an issue with your XQuartz installation. You need to install or update from the XQuartz website. See this thread: https://stackoverflow.com/questions/50398836/rstudio-wont-allow-me-to-install-the-package-imager
After that, try installing pathtrackr again.

**Comment by mulligan123** [comment]
That worked! Thank you so much!
