### ISSUE TITLE
Setting Specific Start Time For splitVideo() 

### ISSUE THREAD

**Issue by brendanmcewen** [aharmer/pathtrackr#20]
Hello,

I have a number of videos that I would like to split but have anywhere from 0-6 seconds of idle time at the start where the animal is not visible (and thus cannot specify the animal in the 'initiation' phase). Is it possible to specify a time in the video file for splitVideo to begin so that I do not have to edit each video? 

Thanks for your time!

**Comment by aharmer** [comment]
Hi,
There is no built in functionality for specifying the start time at the moment. The quickest way to deal with this for now would be to split the video, then remove the files prior to the first appearance of the animal from the split video directory. 
Cheers.

**Comment by brendanmcewen** [comment]
Thanks very much for the reply. I’ll follow your suggestion!
