### ISSUE TITLE
Error: filter height exceeds picture height

### ISSUE THREAD

**Issue by PaulaAV88** [aharmer/pathtrackr#29]
Hi there,
I was able to make the trackPath function work but, after setting the arena and the animal, and is tracking the animal the following error is poping up: 

```
Tracking animal...
  |                                                  |   0%Error in thresh(isoblur(as.cimg(tbox), blur)) : 
  filter height exceeds picture height
```

Any clue what this mean?

**Comment by quentinFABI** [comment]
Hi There!

I am having a similar problem. Did you manage to know what was wrong?

Thanks!

**Comment by Juchartr** [comment]
Hi,

I got the same error. Did you manage to resolve it?

**Comment by PaulaAV88** [comment]
Hi sorry,
I didn't manage to solve it.
