### ISSUE TITLE
trackPath: How to keep original image quality

### ISSUE THREAD

**Issue by ingomiller** [aharmer/pathtrackr#34]
Hey there,

I noticed that trackPath() changes the quality of the images whoch results in a loss of (in this case necessary) contrast. I'm trying to track the movement of a very small animal. Is there a way to tell the trackPath command to not change image quality?

here the command I used:
path.list = trackPath(dirpath = "C:/Users/ingom/Desktop/pathtrackr/output_ffmpeg", xarena = 100, yarena = 200, box = 1, fps = 25)

Thanks in advance!

![image](https://user-images.githubusercontent.com/74630511/99886165-b6b56a80-2c3a-11eb-815b-b21efabc8c4b.png)

**Comment by aharmer** [comment]
Hi,
The image compression occurs in the splitVideo function when you split your video out into individual jpgs. Use the xpix variable in splitVideo and set it to the dimension (in pixels) of your original video to preserve the resolution. Note that the larger the jpg files, the slower the tracking will be.
Regards,
Aaron.
