### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by seroude** [aharmer/pathtrackr#35]
unable to install even when installing from downloaded .gz package:

> > install.packages("~/Downloads/pathtrackr-1.2.3.tar.gz", repos = NULL, type = "source")
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
ERROR: dependencies ‘EBImage’, ‘imager’, ‘viridis’, ‘marmap’, ‘rgdal’, ‘raster’ are not available for package ‘pathtrackr’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/pathtrackr’
Warning in install.packages :
  installation of package ‘/Users/seroudel/Downloads/pathtrackr-1.2.3.tar.gz’ had non-zero exit status

the problem is with dependencies, they are not showing in R studio "install packages".
Did find a way to get EBImage using:

> devtools::install_github("aoles/EBImage")

same problem:

> ERROR: dependency ‘locfit’ is not available for package ‘EBImage’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/EBImage’
Error: Failed to install 'EBImage' from GitHub:

Please aharmer can you help?

**Comment by orijitghosh** [comment]
Install an older version (from 2020) of locfit, it will be compatible with older R versions. Then you can install EBImage from Bioconductor. I also had the same problem.
