### ISSUE TITLE
issues after running trackpath()

### ISSUE THREAD

**Issue by RobertMoore84** [aharmer/pathtrackr#37]
Hello, after I run either trackpath or manual path, i select the boundaries and then the animal boundry it runs however after it does the tracking part it shows

Warning messages:

1: [rast] unknown extent
 2: [rast] unknown extent
 3: [rast] unknown extent
 4: [rast] unknown extent

No idea why tried on many different types of videos

**Comment by aharmer** [comment]
Hi Robert,

Those are just warnings relating to the loading of the raster images. They will not affect the output. I have resolved this in an update that I will release shortly.

Regards,
Aaron.
