### ISSUE TITLE
Error message after defining tracking box

### ISSUE THREAD

**Issue by antoinefelden** [aharmer/pathtrackr#4]
I have trouble running the trackPath function. I used

`trackPath("/Users/antoinefelden/Documents/Research/PhD/experiments/exp_pharmaco/pharmaco_01_data/pharmaco_videos/bold_CTRL_4a", xarena = 90, yarena = 90, fps = 10, box = 2, contrast = 0.5)`

I was able to define on the first image the two points to build the tracking box, but straight after clicking the second point I get the error message
```
Error in as.vector(raster::extent(raster::select(raster::raster(file.list[1],  : 
  no method for coercing this S4 class to a vector
```
Any idea why this happens?

**Comment by aharmer** [comment]
Hi Antoine,
This issue has come up several times and seems to be an issue with conflicting functions in a couple of packages (possibly the select() function from memory, in both raster and dplyr packages). Previous solves were achieved by making sure everything is up to date and manually reloading the raster package to make sure it takes precedence.

**Comment by antoinefelden** [comment]
I checked that the following packages were up to date:
`ggplot2, gridExtra, jpeg, SDMTools, viridis, raster, sp`
and also ran `library(raster)` before re-running `trackPath`, without success. Is that what you meant by manually reloading the package?
Do you have a link to a thread in which the issue was discussed?

**Comment by aharmer** [comment]
Hi Antoine, this fix has worked in the past (can't find a link though sorry). Can you check if you have the 'rgdal' package installed and up to date, reload everything and then try trackPath again?
