### ISSUE TITLE
error message while using install_github()

### ISSUE THREAD

**Issue by rrsarma** [aharmer/pathtrackr#6]
I'm trying to install pathtrackr in a Windows laptop and I have been getting this error throughout  

install_github("arahmer/pathtrackr")
error: installation failed: error setting certificate verified locations:
CAfile:
CApath:none

I can't seem to get pass it.
Please help

**Comment by aharmer** [comment]
Hi, you have spelt the github user name incorrectly, it should be "aharmer/pathtrackr".
