### ISSUE TITLE
empty file with splitVideo

### ISSUE THREAD

**Issue by ErickBarron** [aharmer/pathtrackr#7]
Hi, I've just installed the pathtrack package and I got a problem when I use the splitVideo function.

This is  my code and the warning I got:

splitVideo("C:/Users/Erick B/Desktop/VideoC.MP4", fps = 30)

Warning messages:
1: running command 'ffmpeg -loglevel panic -y -i C:/Users/Erick B/Desktop/VideoC.MP4 -vf scale=320:-1 C:/Users/Erick B/Desktop/VideoC_COMPRESSED.MP4' had status 1 
2: running command 'ffmpeg -loglevel panic -y -i C:/Users/Erick B/Desktop/VideoC_COMPRESSED.MP4 -q:v 2 -vf fps=30 -b:v 2000 -bt 20M C:/Users/Erick B/Desktop/VideoC/frame%06d.jpg' had status 1

After it, I just got an empty folder on my Desktop. 

I'm new on this, so I'll be glad If someone can help me.

**Comment by aharmer** [comment]
Hi Erick, you have a space in your file path, ffmpeg does not like this I believe. I suggest avoiding naming directories and files with spaces in them. It is common practice to use an underscore instead.

**Comment by ErickBarron** [comment]
Hi, thanks for your answer. I really appreciate it.

I did what you recommend me and I still having only an empty folder. This
is my code and the warnings:


splitVideo("C:/Users/VideoA.MP4", fps = 30)

Warning messages:
1: running command 'ffmpeg -loglevel panic -y -i C:/Users/VideoA.MP4 -vf
scale=320:-1 C:/Users/VideoA_COMPRESSED.MP4' had status1
2: running command 'ffmpeg -loglevel panic -y -i
C:/Users/VideoA_COMPRESSED.MP4 -q:v 2 -vf fps=30 -b:v 2000 -bt 20M
C:/Users/VideoA/frame%06d.jpg' had status 1

Could it be a problem with the interaction between my pc and ffmpeg? I´ve
been looking for answers in forums and I can't find a way to solve de
problem.



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by aharmer** [comment]
That's interesting, removing spaces from the file path usually removes this issue. However, the error message indicates that the issue you are having is still at the ffmpeg end and not an R issue. Unfortunately status 1 doesn't tell you much. You can try extracting your still frames using alternative software for now.

**Comment by ErickBarron** [comment]
Yeah, that’s the solution I found in the github forum. Thanks for your answers. 

Erick B.
